### PR TITLE
docs: Added port information

### PR DESCRIPTION
**Pull request by jjperezaguinaga**
Ensured users understand that the service will open two specific ports.

### CODE REVIEW

**Review by DerekJarvis — COMMENTED** [review]
I'm pretty sure these are just local ports, so I'm not sure if the user needs to be made aware of them. This is an intentional improvement from Clay Golem to New Golem. Port forwarding is no longer required, and this might make the users think otherwise.

**Comment by jjperezaguinaga** [comment]
I think this is made on the assumption that `yagna` is run on a computer. When ran on my VM, `yagna` opened these ports. I wonder if this behaviour works on an environment behind a proxy, thus, worth noting and making the difference.

Is this the case? I'll test with some `iptables` rules to `DENY` these ports to see if that's the case.

**Comment by shadeofblue** [comment]
@nieznanysprawiciel do you think such information is relevant? possibly it's good to keep in mind to include in the handbook with the upcoming peer2peer connectivity?

**Comment by jjperezaguinaga** [comment]
Haven't updated this PR in a year, but happy to catch up here and see what changes are needed to showcase this info. Might be easier to just open a new PR and add this content if it's still relevant.

**Comment by nieznanysprawiciel** [comment]
Ports that are mentioned here and p2p are 2 different topics.
`7464` is local port for agent to interact with `yagna` daemon REST API.
`7465` is port for connecting locally to GSB.
Both ports are local, but it would be possible to configure Agent to communicate with `yagna` on different machine.

p2p communication will require opening additional public ports, but we will include this information after releasing hybrid NET.

**Pull request closed without merging**
